global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'node'
  static_configs:
    - targets: ['prom-node-0.prometheus.exokube.eu:9100','prom-node-1.prometheus.exokube.eu:9100']

