global:
  scrape_interval: 5s

scrape_configs:

- job_name: 'prom-boot-consul'
  metrics_path: "/prometheus"
  consul_sd_configs:
    - server: 'localhost:8500'
  relabel_configs:
  - source_labels: [__meta_consul_tags]
    regex: .*,prom-boot,.*
    action: keep
  - source_labels: [__meta_consul_tags]
    regex: .*,version=([^,]+),.*
    replacement: '${1}'
    target_label: version
