global:
  scrape_interval: 5s

scrape_configs:

- job_name: 'prom-boot-dns'
  metrics_path: "/prometheus"
  dns_sd_configs:
    - names:
      - '_prometheus._tcp.prometheus-sd.prometheus.exokube.eu'

